import { useState } from "react";
import { HiDownload, HiChevronDown, HiSparkles } from "react-icons/hi";
import { exportReasoningMarkdown, exportReasoningLatex, exportReasoningNotebook } from "@/lib/api";

interface ExportMenuProps {
    problemId: number;
    code: string;
    reasoning?: string;
    problemName?: string;
}

export function ExportMenu({ problemId, code, reasoning, problemName = "Problem" }: ExportMenuProps) {
    const [showExportMenu, setShowExportMenu] = useState(false);
    const [exporting, setExporting] = useState(false);

    // Convert LaTeX delimiters for Google Docs compatibility (Quick Export)
    const convertLatexForGoogleDocs = (text: string): string => {
        // Convert \(...\) to $...$
        let result = text.replace(/\\\(([\s\S]*?)\\\)/g, '$$$1$$');
        // Convert \[...\] to $$...$$
        result = result.replace(/\\\[([\s\S]*?)\\\]/g, '$$$$$1$$$$');
        return result;
    };

    // Quick Export: Client-side Markdown generation
    const handleQuickExport = () => {
        const currentDate = new Date().toLocaleDateString('en-US', {
            year: 'numeric',
            month: 'long',
            day: 'numeric'
        });

        let markdown = `# ${problemName}\n\n`;
        markdown += `> Generated by NeuronLab AI | ${currentDate}\n`;
        
        if (code) {
            markdown += `\n## Code Solution\n\n\`\`\`python\n${code}\n\`\`\`\n\n`;
        }

        if (reasoning) {
            markdown += `## Reasoning & Solution\n\n`;
            markdown += `> Open in Google Docs with Auto-LaTeX Equations add-on for best experience\n\n`;
            markdown += convertLatexForGoogleDocs(reasoning) + '\n\n';
        }

        // Create and download file
        const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
        const url = URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${problemName?.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'problem'}_export.md`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
        setShowExportMenu(false);
    };

    // AI Enhanced Export (.md)
    const handleAiEnhancedExport = async () => {
        setExporting(true);
        setShowExportMenu(false);
        try {
            const result = await exportReasoningMarkdown(problemId, true);

            const blob = new Blob([result.markdown], { type: 'text/markdown;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            link.download = `${problemName?.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'reasoning'}_enhanced.md`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        } catch (err) {
            console.error('AI Enhanced Export failed:', err);
            // Fall back to quick export if possible, otherwise just alert
            alert('AI Enhanced Export failed. Trying quick export...');
            handleQuickExport();
        } finally {
            setExporting(false);
        }
    };

    // Export LaTeX (.tex)
    const handleExportLatex = async (useSonnet: boolean = false) => {
        setExporting(true);
        setShowExportMenu(false);

        try {
            const result = await exportReasoningLatex(problemId, useSonnet);

            const blob = new Blob([result.latex], { type: 'application/x-tex;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            const suffix = useSonnet ? '_sonnet' : '';
            link.download = `${problemName?.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'reasoning'}_solution${suffix}.tex`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        } catch (err) {
            console.error('LaTeX export failed:', err);
            alert('Failed to export LaTeX. Please try again.');
        } finally {
            setExporting(false);
        }
    };

    // Export Notebook (.ipynb)
    const handleExportNotebook = async (useSonnet: boolean = false) => {
        setExporting(true);
        setShowExportMenu(false);

        try {
            const result = await exportReasoningNotebook(problemId, useSonnet);

            const blob = new Blob([result.notebook], { type: 'application/x-ipynb+json;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const link = document.createElement('a');
            link.href = url;
            const suffix = useSonnet ? '_sonnet' : '';
            link.download = `${problemName?.replace(/[^a-z0-9]/gi, '_').toLowerCase() || 'reasoning'}_solution${suffix}.ipynb`;
            document.body.appendChild(link);
            link.click();
            document.body.removeChild(link);
            URL.revokeObjectURL(url);
        } catch (err) {
            console.error('Notebook export failed:', err);
            alert('Failed to export notebook. Please try again.');
        } finally {
            setExporting(false);
        }
    };

    return (
        <div className="relative font-mono z-20">
            <button
                onClick={() => setShowExportMenu(!showExportMenu)}
                disabled={exporting}
                className={`flex items-center gap-2 px-3 py-2 border-2 transition-colors ${
                    exporting
                        ? "border-cyan-500/50 text-cyan-400 bg-cyan-500/10 cursor-wait"
                        : "border-cyan-500/30 text-cyan-400 hover:bg-cyan-500/10"
                }`}
                title="Export Solution & Reasoning"
            >
                {exporting ? (
                    <>
                        <div className="w-3 h-3 border-2 border-cyan-400 border-t-transparent animate-spin" />
                        <span className="text-xs font-bold">[Exporting...]</span>
                    </>
                ) : (
                    <>
                        <HiDownload className="w-4 h-4" />
                        <span className="text-xs font-bold">[Export]</span>
                        <HiChevronDown className="w-3 h-3" />
                    </>
                )}
            </button>

            {/* Dropdown Menu */}
            {showExportMenu && !exporting && (
                <div className="absolute right-0 top-full mt-1 w-56 bg-[#1a1a2e] border-2 border-gray-700 shadow-xl z-50">
                    <button
                        onClick={handleQuickExport}
                        className="w-full px-4 py-2 text-left text-xs text-gray-300 hover:bg-cyan-500/10 hover:text-cyan-400 transition-colors flex items-center gap-2"
                    >
                        <HiDownload className="w-3 h-3" />
                        <div>
                            <div className="font-bold">[Quick Export]</div>
                            <div className="text-gray-500 text-[10px]">Instant .md download</div>
                        </div>
                    </button>
                    
                    <button
                        onClick={handleAiEnhancedExport}
                        className="w-full px-4 py-2 text-left text-xs text-gray-300 hover:bg-purple-500/10 hover:text-purple-400 transition-colors flex items-center gap-2 border-t border-gray-700"
                    >
                        <HiSparkles className="w-3 h-3" />
                        <div>
                            <div className="font-bold">[AI Enhanced .md]</div>
                            <div className="text-gray-500 text-[10px]">Perplexity + better LaTeX</div>
                        </div>
                    </button>
                    
                    <button
                        onClick={() => handleExportLatex(false)}
                        className="w-full px-4 py-2 text-left text-xs text-gray-300 hover:bg-green-500/10 hover:text-green-400 transition-colors flex items-center gap-2 border-t border-gray-700"
                    >
                        <HiDownload className="w-3 h-3" />
                        <div>
                            <div className="font-bold">[Export .tex]</div>
                            <div className="text-gray-500 text-[10px]">Fast AI LaTeX (pplx_alpha)</div>
                        </div>
                    </button>
                    
                    <button
                        onClick={() => handleExportNotebook(false)}
                        className="w-full px-4 py-2 text-left text-xs text-gray-300 hover:bg-orange-500/10 hover:text-orange-400 transition-colors flex items-center gap-2 border-t border-gray-700"
                    >
                        <HiDownload className="w-3 h-3" />
                        <div>
                            <div className="font-bold">[Export .ipynb]</div>
                            <div className="text-gray-500 text-[10px]">Jupyter Notebook (fast)</div>
                        </div>
                    </button>
                </div>
            )}
        </div>
    );
}
